### ISSUE TITLE
how the router work ?

### ISSUE THREAD

**Issue by akzi** [openim/openim#3]
"maintain location database of all clients, a distributed kv store cluster" and then ?

**Comment by bopjiang** [comment]
1. route the upstream message (client to server side) to service according to the message type.
multiple routing algorithms need be supported.
* round robin
* priority first
* location sense (route to Distribution Service in the same DataCenter? )
configurable for different message type

2. route the downstream message (server to client side) to client according to the Client Identification

**Comment by bopjiang** [comment]
location database is only needed in the second case:  **route the downstream message**

**Comment by Hursa** [comment]
It is time to speed up after 2 or 3 months

**Comment by bopjiang** [comment]
yes, it far behind schedule.  I set up some task in issues. Any one could help, please contact me.
